--
-- Script generated by Source Control for Oracle 1.0.0.0 on 20/02/2018 13:41:23
--
SET DEFINE OFF

CREATE TABLE a_static_data_tables.cciio_template_2_1 (
  "INDICATOR" NUMBER,
  measure_title VARCHAR2(128 BYTE),
  measure_definition VARCHAR2(1024 BYTE),
  oe_metric VARCHAR2(20 BYTE)
);

